name: End-to-End Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:   # ✅ This allows manual + API triggers

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci  # ✅ Recommended before running Cypress

      - name: Cypress Run
        uses: cypress-io/github-action@v5

      - name: Upload Cypress HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report
          path: cypress/reports/html
